### ISSUE TITLE
Open clock programmatically

### ISSUE THREAD

**Issue by tomasz-krol** [Adam5Wu/timedropper#5]
Hi,
is there any way to programmatically open the clock (like `$('#clock').open()`) The only way I found is fire the click event on input:
`clock.dispatchEvent(clcikEvent)`

**Comment by Adam5Wu** [comment]
Yes, it can be done via public APIs:
```
$("#clock2").timeDropper({
	language: 'en',
	animation: 'fade',
	fetchTime: function() {
		return "10:10 AM";
	},
	setTime: function() {},
}).data('TDEx').show();
```

**Comment by tomasz-krol** [comment]
Thanks! :)
